env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - jest
  - import
rules: 
  no-console: 0
  import/extensions: 0
  import/resolver: foo
